### ISSUE TITLE
MyFirst I/O, undefined passed as argument

### ISSUE THREAD

**Issue by olahellgren** [rvagg/learnyounode#124]
```bash
learnyounode -v
learnyounode@1.0.1
```

Trying to use the following code:
```javascript
//My First I/O
var fs = require('fs');
var buffer = new Buffer(fs.readFileSync(process.argv[2]));
console.log(buffer.toString().split('\n').length-1);
```
Works great when using 
`node myfirstio.js file.txt`

When Running `learnyounode run myfirstio.js` I get:
```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
TypeError: path must be a string
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.<anonymous> (D:\nodejs\learnyounode\myfirstio.js:3:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by sigwo** [comment]
Is there anything better to using the 'utf8' option? Is that a better coding practice?
```javascript
// My working example
var fs = require('fs');
console.log(fs.readFileSync(process.argv[2], 'utf8').split('\n').length-1);
```

**Comment by martinheidegger** [comment]
@sigwo WHat do you have in mind?

**Comment by sigwo** [comment]
I'm not sure, that's why I ask. :smile: I am wondering if calling the raw text from `process.argv` is common practice or if there is a newer/better/more accepted way? As in '.toString()'? Or ?

**Comment by martinheidegger** [comment]
The `process.argv` is a string array unless someone mingles with it. the "utf8" part is not for the `process.argv` its for `readFileSync`.  `readFileSync` will return a Buffer instead of a String if "utf8" isn't passed.

**Comment by sigwo** [comment]
What is the difference between buffer and string?

**Comment by martinheidegger** [comment]
http://nodejs.org/api/buffer.html#buffer_buffer

**Comment by sigwo** [comment]
If I read this correctly, it is a BBP to declare the string encodings for speed (possibly security?) and ease of troubleshooting, since you can readily see in the code what it is expecting.

Or I totally missed the lesson here :cry:

**Comment by rvagg** [comment]
In standard usage I'd opt for `'utf8'` when I want a string, it's not mentioned in MY FIRST I/O for two reasons:
 1. Introduce the `Buffer` concept early, it's important to have at least a brief exposure to it because it's so fundamental
 2. Avoid introducing another concept to have to explain--even if it said to use `'utf8'` then we'd have to explain what that's doing and would hit `Buffer` anyway.

In general, it's important to keep these exercises as simple as possible because the more there is to explain the less people will read.

**Comment by rvagg** [comment]
on the original topic of this issue -- I have a feeling this may be to do with a windows junction/link problem that's come up a few times but I _believe_ was fixed somewhere along the way.

It'd be great to hear if the original poster still has the same problem with learnyounode@2.4.0

**Comment by sigwo** [comment]
Thanks @rvagg, understood. I am thoroughly enjoying the coursework. :+1:

**Comment by olahellgren** [comment]
After installing learnyounode@2.5.0 I now pass the test.
