### ISSUE TITLE
Colorless output

### ISSUE THREAD

**Issue by travs** [rvagg/learnyounode#159]
I want to save the contents of a lesson to a file by using `learnyounode print > filename`.

Is there a way to enable colorless output, so I can save the contents of a lesson without escape codes showing up in the saved file? 

I know I can do this with `sed`, `awk` and the like, but it might be a good feature.

If this does not exist, which dependency should I be making changes/pull requests to?

**Comment by martinheidegger** [comment]
There is is a `--no-color` option but it has [a bug](https://github.com/rvagg/workshopper/issues/75).
