### ISSUE TITLE
No output - Filtered LS

### ISSUE THREAD

**Issue by bnb** [rvagg/learnyounode#162]
I can't figure out why I'm not getting any output from the script that I've written for Filtered LS.  I'm pretty sure it has something to do with my loop, but I don't see what's wrong with it--everything looks like it should work perfectly to me. Could you help me identify the problem?

```JavaScript
var fs   = require('fs');
var path = require('path');

var inputPath = process.argv[2];
var inputExt  = process.argv[3];

fs.readdir(inputPath, function (err, list) {
    if (err) {
        return err;
    }
    for (var i = 0; i < list.length; i++) {
        var exts = path.extname(list[i]);
        if (exts === inputExt) {
            var popped = inputPath + exts.split('\n').pop();
            console.log(popped);
        }
    }
});

```

**Comment by abbondanza** [comment]
@bnb, it is okay to use for instead of forEach. But you have to make sure you are comparing the right extensions in your if statement. the path.extname function returns the extension with the period before it. Plus, all you need to log is the current list item. This works:

``` js
var fs   = require('fs');
var path = require('path');

var inputPath = process.argv[2];
var inputExt  = process.argv[3];

fs.readdir(inputPath, function (err, list) {
    if (err) {
        return err;
    }
    for (var i = 0; i < list.length; i++) {
        var exts = path.extname(list[i]);
        if (exts === '.'+inputExt) {
            console.log(list[i]);
        }
    }
});
```

**Comment by martinheidegger** [comment]
Seems resolved.
