### ISSUE TITLE
FILTERED LS is not working correctly

### ISSUE THREAD

**Issue by sivadosapati** [rvagg/learnyounode#166]
I'm having trouble with executing Exercise 5 (FILTERED LS). My code certainly works with 

node program.js directory-name file-extension

but with the following command, it's not working

learnyounode run program.js directory-name file-extension

This prints some random directories for directory-name and file-extension. Please find part of the output
<pre>
0 : /usr/local/bin/node
1 : /Users/dosapats/projects/node/learnyounode/program.js
2 : /var/folders/56/1yb7t_7x4099zwdlcyzg8cz0mr7scz/T/_learnyounode_23210
3 : md
/usr/local/bin/node
/Users/dosapats/projects/node/learnyounode/program.js
/var/folders/56/1yb7t_7x4099zwdlcyzg8cz0mr7scz/T/_learnyounode_23210
md
</pre>
Code in program.js
<pre>
var fs = require("fs");
var path = require("path");
var argv = process.argv;
for( var i in argv){
   console.log( i + " : "+ argv[i]);
}
console.log(argv[0]);
console.log(argv[1]);
console.log (argv[2])
console.log(argv[3]);
console.log("-----------------------");
fs.readdir(argv[2],function(err,files){
   for(var i =0;i<files.length;i++){
      var file = files[i];
      console.log("File Name -> "+file);
      var ext = path.extname(file);
      if( ext!="."+argv[3]){
         console.log(file);
      }
   }
});
</pre>

**Comment by rvagg** [comment]
if you want to test it with your own directory and extension then just run the program as you are doing but when you `learnyounode run` or `learnyounode verify` it sets up a test environment and executes your program against it, supplying its own arguments.

**Comment by sivadosapati** [comment]
Thank you..
