### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by ClimbsRocks** [rvagg/learnyounode#167]
I noticed the API Docs referenced haven't been updated in a year. I'd be happy to update them from v0.10.24 to v0.10.35 if you're open to it. The formatting has changed noticeably in that time, so it would be nice for people to get used to using docs that match the current layout. 

Alternatively, if you're open to it, I could point all the links to the online node documentation, to avoid the need to update again in the future. 

Let me know how I can be helpful!

Thanks,
preston

**Comment by martinheidegger** [comment]
The offline documentation is there in case we have network problems. I think a PR with the updated docs would be welcome!

**Comment by ClimbsRocks** [comment]
Great, I just submitted one! 

https://github.com/rvagg/learnyounode/pull/168

Let me know if there's anything else I can do to help.

**Comment by martinheidegger** [comment]
@ClimbsRocks You could review/test the translation :smile: 

https://github.com/rvagg/workshopper/pull/74#issuecomment-68429699
