### ISSUE TITLE
keep the MIT +no-false-attribs license or change to plain MIT?

### ISSUE THREAD

**Issue by ralphtheninja** [rvagg/learnyounode#186]
`node-leveldown` and others have changed to plain MIT. Is this something we should change for `learnyounode` as well? I have no opinion on which one to use, just want to hear your thoughts.

**Comment by Flet** [comment]
+1 plain MIT

For those who want some history, here is the related discussion from other repo(s): Level/level-packager/issues/1

**Comment by ralphtheninja** [comment]
https://github.com/rvagg/learnyounode/commit/818bd4bd252616da7651ba3b12e34680c7164c1e
