### ISSUE TITLE
Make it modular test bug.

### ISSUE THREAD

**Issue by tomcat1911** [rvagg/learnyounode#200]
Test:  "Additional module file returned correct number of elements as the second argument of the callback" was passed, but the next test: "Your additional module file [mymodule.js] did not return an Array with the correct number of elements as the second argument of the callback" wasn't.
 My module:
```javascript
var fs = require('fs');

module.exports = function getFiles(dir, ext, callback) {
	fs.readdir(dir, function(err, data) {
		if (err) 
			return callback(err);
		callback(null, data);
	});
}
```
And main.js:
```javascript
var getFiles = require('./mymodule');
var dir = process.argv[2];
var ext = process.argv[3];

getFiles(dir, ext, function(err, data) {
	for (var i = 0; i < data.length; i++) {
		if (data[i].split('.')[1] === ext)
			console.log(data[i]);
	}
});
```

**Comment by martinheidegger** [comment]
@tomcat1911 This is not a "bug" but an understanding problem. Your module is supposed to only return entries that match the extension and not all entries.
