### ISSUE TITLE
Doesn't look good under solarized color scheme

### ISSUE THREAD

**Issue by yegle** [rvagg/learnyounode#210]
Not sure if anyone is using solarized in their terminal...

The current color scheme doesn't work well under solarized color scheme. I'm using iTerm2 in OS X.

If it's not possible to change the color scheme, at least there should be an option to turn off color highlighting.

![screen shot 2015-02-02 at 2 24 02 pm](https://cloud.githubusercontent.com/assets/146133/6010436/362b173c-aae7-11e4-9415-e3ffb0548941.png)

**Comment by Flet** [comment]
dupe of #96 ?

**Comment by yegle** [comment]
My apologies, I searched this repo for solarized but forgot the default searching result is for code search :-(
