### ISSUE TITLE
Exercise 3 problem

### ISSUE THREAD

**Issue by ccysfn** [rvagg/learnyounode#249]
Here is my "program.js":
```
var buf=fs.readFileSync('xxx');
```
What location should i type in instead of 'xxx'?

**Comment by tgfjt** [comment]
The path will be provided as the first command-line argument. e.g. `node program.js PATH/TO/FILE.txt`

**Comment by ccysfn** [comment]
Thanks a lot !
You didn't give me the answer ,but give me the way to solve .
I did it!   plz close this issue.
