### ISSUE TITLE
leanyounode doesn't work in Windows 7 console

### ISSUE THREAD

**Issue by rrsqrd** [rvagg/learnyounode#252]
I am attempting to run learnyounode on a windows 7 Levovo laptop. (it is brand new)
I have git bash and node.js installed.
When I run learnyounode it displays the blue menu listing the exercises but
the cursor returns to the command line prompt and thus you can't make a selection.
This happens both in a git bash console and dos console.
A peer also had the same problem on a Windows system.

![learnyounodeconsolefailure](https://cloud.githubusercontent.com/assets/7317548/6722745/32a56e50-cdb5-11e4-8aeb-e2321f8056c7.PNG)
thanks

**Comment by martinheidegger** [comment]
@rrsqrd I am not quite sure what the problem is but I saw this only once before (hard to reproduce). Can you run `npm config ls` `npm -v` `node -v` `learnyounode -v`?

**Comment by rrsqrd** [comment]
$ npm config ls nmp -v node -v learnyounode -v
1.3.2  

Btw, not sure if it matters, but I should mention that nodejs was installed on my system
as part of Aptana Studio 3 installation.   Control panel programs shows it is from 
"Joyent Inc and other Node contributors".
$ node --version
v0.10.13

thanks
