### ISSUE TITLE
Other languages?

### ISSUE THREAD

**Issue by mdunisch** [rvagg/learnyounode#92]
Hi,

i really enjoyed nodeschool.io - great work!

Have you planed to offer it in other languages? I can help you translate to german if you want.

Especially the hints are not so easy to understand if english is not your native language

**Comment by martinheidegger** [comment]
Duplicate: https://github.com/rvagg/learnyounode/issues/126 @mdunisch I am working on a completely translated learnyounode where I need help with here: https://github.com/rvagg/workshopper/pull/74#issuecomment-68429699
